name: Build and Push docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  dockerpush:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        name: Build the Docker image
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: use action for docker push
        with:
          image: anandka2000/ldockeranand/heros-app
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#jobs:
#  dockerpush:
#    runs-on: ubuntu-latest
#    steps: 
#      - uses: actions/checkout@v2
#        name: Build the Docker image
#      - run: docker build . --file Dockerfile --tag docker.io/${{ secrets.DOCKER_USERNAME }}/ldockeranand/heros-app
#      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
#      - run: docker image push docker.io/${{ secrets.DOCKER_USERNAME }}/ldockeranand/heros-app
