name: Build and Push docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dockerpush:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        name: Build the Docker image
      - run: docker build . --file Dockerfile --tag docker.io/tech5/heros-app:$(date +%s)
      - run: docker login ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker image push docker.io/tech5/heros-app:$(date +%s)
