name: Build and Push docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.io/tech5/heros-app:$(date +%s)
      run: docker login ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      run: docker image push docker.io/tech5/heros-app:$(date +%s)
      

    # - uses: mr-smithers-excellent/docker-build-push@v5
     #  with:
      #  image: tech5/heros-app
       # registry: docker.io
        #username: ${{ secrets.DOCKER_USERNAME }}
        #password: ${{ secrets.DOCKER_PASSWORD }}
