name: run-heros-app
on: [push]
jobs:
  heros-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - name: tests
        uses: ./
        with:
          # wait for the URL to respond
          # using the default parameter
          start: npm start
          wait-on: 'http://localhost:3050'
